Toolshare/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('',
    url(r'^', include('tools.urls', namespace="tools")),
)

tools/urls.py
from django.conf.urls import patterns, url
from tools.views import index_controller, detail_controller, login_controller, register_controller,list_controller, \
    renttool_controller, returntool_controller, userpage_controller, reviewuser_controller

urlpatterns = patterns('',
    url(r'^login', login_controller.login, name='login'),
    url(r'^$', index_controller.index, name="tools"),
    url(r'^(?P<tool_id>\d+)/$', detail_controller.detail, name='detail'),
    url(r'^register', register_controller.register, name='register'),
    url(r'^list', list_controller.list, name='list'),
    url(r'^rent', renttool_controller.renttool, name='rent'),
    url(r'^returntool', returntool_controller.returntool, name='returntool'),
    url(r'^user', userpage_controller.userpage, name='user'),
    url(r'^review', reviewuser_controller.reviewuser, name='review')
)

tools/models.py
from django.db import models
from django.contrib.auth.models import User

class Community(models.Model):
    zip_code = models.IntegerField()
    def num_members(self):
        member_list = UserProfile.objects.filter(community = self)
        return len(member_list)
    def __str__(self):
        return str(self.zip_code)

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    community = models.ForeignKey(Community)
    sharer_rating = models.FloatField(default=0)
    sharer_rating_count = models.IntegerField(default=0)
    borrower_rating = models.FloatField(default=0)
    borrower_rating_count = models.IntegerField(default=0)
    def numrent(self):
        my_tool_list = Tool.objects.filter(owner = self)
        if len(my_tool_list) > 5:
            return 5
        else:
            return len(my_tool_list)
            
    def canrent(self):
        nrent = 0
        my_tool_list = Tool.objects.filter(owner = self)
        if len(my_tool_list) > 5:
            nrent = 5
        else:
            nrent = len(my_tool_list)
        my_rent_list = Rent.objects.filter(renter = self, returned = 0)
        if len(my_rent_list) < nrent:
            return 1
        else:
            return 0
 
    def __str__(self):
        return self.user.username
    
class Tool(models.Model):
    owner = models.ForeignKey(UserProfile)
    tool_name = models.CharField(max_length=30)
    tool_desc = models.CharField(max_length=512)
    TOOL_TYPE_CHOICES = (
            (0,"Powertool"),
            (1,"Construction"),
            (2,"Automotive"),
            (3,"Garden"),
            (4,"Other"),
            )
    tool_type = models.IntegerField(choices=TOOL_TYPE_CHOICES)
    def rentable_default():
        return 1
    rentable = models.BooleanField(default=rentable_default)
    def requested(self):
        request_list = RentRequest.objects.filter(tool_requested = self, req_status = 0)
        if len(request_list) > 0:
            return 1
        else:
            return 0
    def __str__(self):
        return self.tool_name

class Rent(models.Model):
    time_rented = models.DateTimeField(auto_now=True)
    time_returned = models.DateTimeField(null=True)
    tool_rented = models.ForeignKey(Tool)
    renter = models.ForeignKey(UserProfile)
    def returned_default():
        return 0
    returned = models.BooleanField(default=returned_default)
    def __str__(self):
        return self.renter.user.username + ' ' + self.tool_rented.tool_name

class todoReview(models.Model):
    time_created = models.DateTimeField(auto_now=True)
    todo_reviewee = models.ForeignKey(UserProfile, related_name='todo_reviewee')
    todo_reviewer = models.ForeignKey(UserProfile, related_name='todo_reviewer')
    todo_tool = models.ForeignKey(Tool, related_name = 'todo_tool')
    todo_review_type = models.BooleanField(default = 0)
    def __str__(self):
        return str(self.todo_reviewee) + '(' + str(self.todo_review_type) + ')' + str(self.todo_reviewer)

class Review(models.Model):
    time_reviewed = models.DateTimeField(auto_now=True)
    rating = models.IntegerField(default = 0)
    comment = models.CharField(max_length=512)
    reviewer = models.ForeignKey(UserProfile, related_name='reviewer')
    reviewee = models.ForeignKey(UserProfile, related_name='reviewee')
    review_type = models.BooleanField(default = 0)
    def __str__(self):
        return str(self.reviewee) + '(' + str(self.review_type) + ')' + ':' + str(self.rating)

class RentRequest(models.Model):
    req_time = models.DateTimeField(auto_now=True)
    dec_time = models.DateTimeField(null=True)
    owner = models.ForeignKey(UserProfile, related_name='owner')
    requester = models.ForeignKey(UserProfile, related_name='requester')
    STATUS_CHOICES = (
            (0,"Waiting for Response"),
            (1,"Approved"),
            (2,"Denied"),
            )
    req_status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    tool_requested = models.ForeignKey(Tool) 
    def tool_owner(self):
        return self.tool_requested.owner
    def __str__(self):
        return '<'+ str(self.req_time) + '> Tool: ' + str(self.tool_requested) + ' Status:' + str(self.req_status)

tools/views/detail_controller.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from tools.models import Tool,UserProfile,Rent,RentRequest

"""
	detail(request, tool_id)
	View handler for tool detail page
"""
def detail(request, tool_id):
    delete = None
    user = None
    rent = None
    if request.user.is_authenticated():
        tool = Tool.objects.filter(pk=tool_id)
        user_profile = UserProfile.objects.get(user=request.user)
        if len(tool) == 0:
            return HttpResponseRedirect(reverse('tools:tools'))
        else:
            tool = Tool.objects.get(pk=tool_id)
            if tool.owner.community == user_profile.community:
                request_list = RentRequest.objects.filter()
                tool_request_list = RentRequest.objects.filter(tool_requested = tool, req_status = 0)
                myrequest = RentRequest.objects.filter(requester = user_profile, tool_requested = tool, req_status = 0)
                if (tool.rentable == 0): 
                    checkrent = Rent.objects.filter(tool_rented = tool, returned = 0)
                    if len(checkrent) != 0:
                        rent = Rent.objects.get(tool_rented = tool, returned = 0)
                context = {'myrequest':myrequest, 'tool': tool, 'rent': rent, 'user': user_profile, 'request_list' : request_list, 'tool_request_list' : tool_request_list}
                return render(request, 'tools/detail.html', context)
            else:
                return HttpResponseRedirect(reverse('tools:tools'))
    return HttpResponseRedirect(reverse('tools:login'))

tools/views/error_controller.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from tools.models import UserProfile

def error(request):
    if request.user.is_authenticated():
        
    return HttpResponseRedirect(reverse('tools:tools'))

tools/views/index_controller.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from tools.models import Tool,UserProfile,Community,RentRequest
    
"""
	index(request)
	View handler for tools index page
"""
def index(request):
    if request.user.is_authenticated():
        user_profile = UserProfile.objects.get(user=request.user)
        user_list = UserProfile.objects.filter(community=user_profile.community).order_by('user').exclude(user = user_profile.user)
        tool_list = Tool.objects.filter().order_by('-rentable', '-pk').exclude(owner=user_profile)
        request_list = RentRequest.objects.filter()
        context = {'tool_list': tool_list, 'user_list' : user_list, 'user': user_profile, 'request_list' : request_list}
        return render(request, 'tools/index.html', context)
    return render(request, 'tools/login.html', None)

tools/views/list_controller.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from tools.models import Tool,UserProfile,Community,Rent,RentRequest
    
"""
	list(request)
	View handler for tool listing page.
	Handles displaying listing form, creating the new tool & deleting tools.
"""
def list(request):
    user = None
    tool = None
    name_message = ''
    desc_message = ''
    alert_message = ''
    tool_id = None
    tool_name=''
    tool_desc=''
    tool_type_id=4
    rentable = 1
    #only show page if use is auth'd
    if request.user.is_authenticated():
        user_profile = UserProfile.objects.get(user=request.user)
        tool_list = Tool.objects.filter(owner = user_profile).order_by('-pk')
        request_list = RentRequest.objects.filter( )
        if request.method == 'GET':
            if 't' in request.GET:
                if 'a' in request.GET:
                    tool_id = request.GET['t']
                    tool = Tool.objects.get(pk=tool_id)
                    if request.GET['a'] == '0':
                        tool_name = tool.tool_name
                        tool_desc = tool.tool_desc
                        tool_type_id = tool.tool_type
                        rentable = tool.rentable
                    elif request.GET['a'] == '1':
                        if tool.owner == user_profile:
                            tool.delete()
                        return HttpResponseRedirect(reverse('tools:tools'))
        elif request.method=='POST':
            #get the tool information
            tool_id = request.POST.get('tool_id')
            if(tool_id):
                tool = Tool.objects.get(pk=tool_id)
            tool_name = request.POST['tool_name']
            name_check = tool_name.strip() #strip() gets rid of all whitespace
            
            tool_desc = request.POST['tool_desc']
            desc_check = tool_desc.strip() #strip() gets rid of all whitespace
            
            tool_type_id = int(request.POST.get('tool_types'))
            tool_type = Tool.TOOL_TYPE_CHOICES[int(tool_type_id)]
            
            rentable = request.POST.get('rentable')
            if not rentable:
                rentable = 0
            else:
                rentable = 1
            
            if not ((name_check) and (desc_check)) or (len(tool_name)>30 or len(tool_desc)>512): #are either of them empty?
                if not (name_check): #if name is empty
                    name_message = "Tool name is blank." 
                elif (len(tool_name)>30):
                    name_message = "Tool name is " + str(abs(30-len(tool_name))) + " characters longer than 30."
                if not (desc_check): #if desc is empty
                    desc_message = "Tool description is blank."
                elif (len(tool_desc)>512):
                    desc_message = "Tool description is " + str(abs(512-len(tool_desc))) + " characters longer than 512." 
            elif (tool):
                    #edits tool attributes and save
                    tool = Tool.objects.get(pk=tool_id)
                    tool.tool_name = tool_name
                    tool.tool_desc = tool_desc
                    tool.tool_type = tool_type_id
                    tool.rentable = rentable
                    tool.save()
                    
                    #display message for bottom of the screen
                    alert_message = (tool_name) + " Updated!"
            else:
                    #create the new tool with them as the owner
                    user_profile.tool_set.create(tool_name=tool_name, tool_desc=tool_desc, tool_type = tool_type_id, rentable = rentable)
                    #and save the tool to the database
                    user_profile.save()
                    
                    #display message for bottom of the screen
                    alert_message = (tool_name) + " Created!"
                    
                    #reset saved data so new tool can be created
                    user = None
                    tool = None
                    name_message = ''
                    desc_message = ''
                    tool_id = None
                    tool_name=''
                    tool_desc=''
                    tool_type_id=4
                    rentable = 1
 
        context = {'rentable':rentable, 'request_list':request_list, 'tool_list':tool_list, 'alert_message':alert_message, 'tool_id':tool_id, 'tool_name':tool_name, 'tool_desc':tool_desc, 'tool_type_id':tool_type_id, 'tool':tool, 'desc_message':desc_message, 'name_message':name_message, 'user' : user_profile, 'tool_types' : Tool.TOOL_TYPE_CHOICES  }
        return render(request, 'tools/list.html', context)
    return HttpResponseRedirect(reverse('tools:login'))

tools/views/login_controller.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import authenticate, logout, login as auth_login
from tools.models import UserProfile

"""
	login(request)
	View handler for the login page.
	Includes both displaying form and internally authenticating users.
"""
def login(request):
    #if the HTTP request method is POST, we know the login form was submitted
    if request.method == 'POST':
        #get the entered username and password from the request
        user_name = request.POST['user_name']
        password = request.POST['passwd']
        #attempt to auth the user
        user = authenticate(username=user_name, password=password)
        if user and user.is_active:
            #log in user in session if auth'd and user is active,
            #and return to the index page
            auth_login(request, user)
            return HttpResponseRedirect(reverse('tools:tools'))
        else:
            #otherwise, tell them login was invalid
            context = {'message': "Invalid login!"}
            return render(request, 'tools/login.html', context)
    else:
        #if not post, method is GET - the standard method for page browsing
        if 'a' in request.GET and request.GET['a'] == '1':
            #if ?a=1, log out and return user to index page
            logout(request)
            return HttpResponseRedirect(reverse('tools:tools'))
        else:
             #otherwise, just render the login form page
             return render(request, 'tools/login.html')

tools/views/register_controller.py
import re
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from tools.models import UserProfile,Community

"""
	register(request)
	View handler for the user registration page.
	Handles both displaying the form and creating the new user.
"""
def register(request):
    if (request.method == 'POST'):
        #get the values entered in the form
        user_name = request.POST['user_name']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        zip = request.POST['zip_code']
        passwd = request.POST['passwd']
        passwd2 = request.POST['passwd2']
        over18 = request.POST.get('over18')
        
        #strip whitespace
        user_name_check = user_name.strip()
        first_name_check = first_name.strip()
        last_name_check = last_name.strip()
        zip_check = zip.strip()
        passwd_check = passwd.strip()
        passwd2_check = passwd.strip()
       
        #validate input
        errors = 0
        message = [None] * 6
        if not ( isEmail(user_name) ):
            message[0] = "Email is not a valid email."
            errors+=1
        elif User.objects.filter(username=user_name):
            message[0] = "Email already exists!"
            errors+=1
        if not ( first_name_check ):
            message[1] = "First Name is blank."
            errors+=1
        if not ( last_name_check ):
            message[2] = "Last Name is blank."
            errors+=1
        if not ( isZip(zip) ):
            message[3] = "Zip is invalid."
            errors+=1
        if not ( passwd_check ):
            message[4] = "Password is blank."
            errors+=1
        if ( passwd != passwd2 ):
            message[4]= "Passwords do not match."
            errors+=1
        if not (over18):
            message[5] = "You are not over 18."
            errors+=1
        
        #create user if no errors
        if not ( errors ):
            #check community exists
            if (not Community.objects.filter(zip_code=zip)):
                c = Community(zip_code=zip)
                c.num_members = 0
                c.save()
            #create the user profile and save it to the database
            u = UserProfile(community=Community.objects.get(zip_code=zip))
            u.user = User.objects.create_user(user_name, user_name,passwd)
            u.user.first_name = first_name
            u.user.last_name = last_name
            u.user.save()
            u.save()
            return render(request, 'tools/login.html')
        #pass fields back on error.
        context = { 'over18':over18, 'user_name' : user_name, 'first_name' : first_name, 'last_name' : last_name, 'zip_code' : zip, 'message':message }
        return render(request, 'tools/register.html', context)
    return render(request, 'tools/register.html')

def isZip(str):
    i = 0;
    for u in list(str):
        if ( u.isdigit() ):
            i = i + 1
        else:
            return 0;
    if ( i == 5 ):
        return 1
    return 0

def isEmail(str):
    r = re.compile(r"[^@]+@[^@]+\.[^@]+")
    if not r.match(str):
        return 0
    return 1

tools/templates/tools/addtool_block.html
{% load staticfiles %}

<td>
    <dir id="block">
        <center>
            Add Tool
            <br>
            <br>
            <a href="{%url 'tools:list'%}"><img id="pic" src="{% static 'tools/add.png' %}"/></a>
        </center>
    </dir>
</td>

tools/templates/tools/banner.html
{% load staticfiles %} 

<dir id = "banner">
	<center><a href="{% url 'tools:tools' %}"><img id="bannerpic" src="{% static 'tools/banner.png' %}"/></a></center>
	<br>
    {% if user.user.is_authenticated%}
    <dir id = "nav">
    <ul>
        <li class="auth">
            <a href="{% url 'tools:tools' %}" id="nav">
                <table>
                    <tr>
                        <td>
                            <img id="pic_small" src="{% static 'tools/home.png' %}"/>
                        </td>
                        <td>
                            <font size=4>Home</font>
                        </td>
                    </tr>
                </table>
            </a> 
        </li>
        <li class="auth">
            <a href="{%url 'tools:list'%}"id="nav">
                <table>
                    <tr>
                        <td>
                            <img id="pic_small" src="{% static 'tools/register.png' %}"/>
                        </td>
                        <td>
                            <font size=4>Register Tool</font>
                        </td>
                    </tr>
                </table>
            </a>
        </li>
        <li class="auth">
            <a href="{% url 'tools:user' %}?u={{user.pk}}"id="nav">
                <table>
                    <tr>
                        <td>
                            <img id="pic_small" src="{% static 'tools/user.png' %}"/>
                        </td>
                        <td>
                            <font size=4>{{user.user.first_name}}</font>
                        </td>
                    </tr>
                </table>
            </a> 
        </li>
        <li class="auth">
            <a href="{%url 'tools:login'%}?a=1"id="nav">
                <table>
                    <tr>
                        <td>
                            <img id="pic_small" src="{% static 'tools/logout.png' %}"/>
                        </td>
                        <td>
                            <font size=4>Log Out</font>
                        </td>
                    </tr>
                </table>
            </a> 
        </li>
    </ul>
    {% else %}
    <dir id = "nav">
    <ul>
        <li class="unauth">
            <a href="{%url 'tools:login'%}"id="nav">
                <table>
                    <tr>
                        <td>
                            <img id="pic_small" src="{% static 'tools/login.png' %}"/>
                        </td>
                        <td>
                            <font size=4>Log In</font>
                        </td>
                    </tr>
                </table>
            </a>
        </li>
        <li class="unauth">
            <a href="{%url 'tools:register'%}"id="nav">
                <table>
                    <tr>
                        <td>
                            <img id="pic_small" src="{% static 'tools/register.png' %}"/>
                        </td>
                        <td>
                            <font size=4>Register</font>
                        </td>
                    </tr>
                </table>
            </a>
        </li>
    </ul>
    {% endif %}
    </dir>
</dir>

tools/templates/tools/detail.html
{% load staticfiles %}
<head>
	<link rel="stylesheet" type="text/css" href="{% static 'tools/style.css' %}" />
</head>
{% include "tools/banner.html" %}

<dir>
    <center>
        {% include "tools/status.html" %}
        <font size="6">{{tool.tool_name}} </font>
            
        <table id = "information">
            <tr >
                <td>
                    <big>Owner: </big>
                </td>
                <td>
                    {% if tool.owner == user %}
                        <a href="{% url 'tools:user' %}?u={{tool.owner.pk}}">You own this tool</a>
                    {% else %}
                        <a href="{% url 'tools:user' %}?u={{tool.owner.pk}}">{{ tool.owner.user.get_full_name }}</a>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td>
                    <big>Desc: </big>
                </td>
                <td>
                    {{tool.tool_desc}}
                <td>
            </tr>
            <tr>
                <td>
                    <big>Type: </big>
                </td>
                <td>
                    {{tool.get_tool_type_display}}
                <td>
            </tr>
        </table>
            
        <br>
        {% include "tools/icon.html" %}
        <br>
        {% if tool.owner == user %}
            {% if not rent %}
                <table>
                     <tr>
                        <td>
                            <a href="{%url 'tools:list'%}?a=0&t={{tool.pk}}"id="button">Edit</a>
                        </td>
                        <td>
                            <a href="{%url 'tools:list'%}?a=1&t={{tool.pk}}" id="deletebutton"onclick="makeAlert()">Remove</a>
                        </td>
                    </tr>
                </table>
            {% else %}
                <table>
                     <tr>

                        <td>
                            <dir id="deadbutton">Edit</dir>
                        </td>
                        <td>
                            <dir id="deadbutton">Remove</dir>
                        </td>
                    </tr>
                </table>
            {% endif %}
            
            {% if rent %}
                Currently rented by: {{rent.renter.user.get_full_name}}
            {% elif not rent and not tool.rentable %}
                Tool is not being shared.
            {% endif%}
        {%else%}
            {%if rent %}
                {% if rent.renter == user %}
                    <a href="{%url 'tools:returntool'%}?u={{user.pk}}&t={{tool.pk}}"id="button">Return</a>
                {% else %}
                    <dir id="deadbutton">Borrow</dir>
                    {% if rent %}
                        Currently rented by: {{rent.renter.user.get_full_name}}
                    {% endif %}
                {% endif %}
            {% else %}
                {% if not user.canrent %}
                    <dir id="deadbutton">Borrow</dir>
                    {% if user.numrent == 0 %}
                        You can't rent a tool because you have no tools registered.
                    {% else %}
                        You're renting your maximum amount of tools ({{user.numrent}}).
                    {% endif %}
                {% else %}
                    {% if tool.rentable == 1 and not myrequest and user.canrent %}
                        <a href="{%url 'tools:rent'%}?u={{user.user.pk}}&t={{tool.pk}}"id="button">Borrow</a>
                    {% elif not rent and not tool.rentable %}
                        <dir id="deadbutton">Borrow</dir>
                        Tool is not being shared.
                    {% else %}
                        <dir id="deadbutton">Borrow</dir>
                        You already requested this tool!
                    {% endif %}
                {% endif %}
            {% endif %}
        {% endif %}
    </center>
</dir>
{%if tool.owner == user %}
    <dir>
        <font size="6">Requests</font>
            <dir id="scrollable">
                <table>
                    <tr>
                        {% for request in tool_request_list %}
                            {% include "tools/request_block.html" %}
                        {% endfor %}
                    </tr>
                 </table>
            </dir>
            {% if not tool_request_list %}
                You have no requests for this tool!
            {% endif %}
    </dir>
{% endif %}
<script>
function makeAlert() {
    var x;
    if (confirm("Are you sure you want to delete this tool?") == true) {
        x = "{%url 'tools:list'%}?a=1&t={{tool.pk}}"
    } else {
        x = "{% url 'tools:detail' tool.id %}"
    }
    document.getElementById("deletebutton").setAttribute("href", x);
}
</script>

tools/templates/tools/myrequest_block.html
{% load staticfiles %}

<td>
    <dir id="block">
            <table>
                <tr>
                    <td>
                        {% include "tools/smallicon.html" %}
                    </td>
                    <td>
                        <a href="{% url 'tools:detail' myrequest.tool_requested.pk %}">{{ myrequest.tool_requested.tool_name }}</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <img id="pic_small" src="{% static 'tools/user.png' %}"/>
                    </td>
                    <td>
                        <a href="{% url 'tools:user' %}?u={{request.requester.pk}}">{{ myrequest.requester.user.get_full_name }}</a>
                    </td>
                </tr>                
            </table>
            Status:
            <br>
            {% for key, value in status_choices %}
                {% if key == myrequest.req_status %}
                    {{value}}
                {% endif%}
            {% endfor %}
    </dir>
</td>

tools/templates/tools/request_block.html
{% load staticfiles %}

<td>
    <dir id="block">
            <table>
                <tr>
                    <td>
                        {% include "tools/smallicon.html" %}
                    </td>
                    <td>
                        <a href="{% url 'tools:detail' request.tool_requested.pk %}">{{ request.tool_requested.tool_name }}</a>
                    </td>
                </tr>
                <tr>
                    <td>
                        <img id="pic_small" src="{% static 'tools/user.png' %}"/>
                    </td>
                    <td>
                        <a href="{% url 'tools:user' %}?u={{request.requester.pk}}">{{ request.requester.user.get_full_name }}</a>
                    </td>
                </tr>                
            </table>
            {% if request.tool_requested.rentable and request.requester.canrent %}
                <a href="{% url 'tools:rent' %}?a=1&r={{request.pk}}"id="button">Accept</a>
                <a href="{% url 'tools:rent' %}?a=0&r={{request.pk}}"id="button">Deny</a>
            {% else %}
                <dir id="deadbutton">Accept</dir>
                <dir id="deadbutton">Deny</dir>
            {% endif %}
    </dir>
</td>

tools/templates/tools/review_block.html
{% load staticfiles %}

<td>
    <dir id="block">
            <table>
                <tr>
                    <td>
                        <img id="pic_small" src="{% static 'tools/user.png' %}"/>
                    </td>
                    <td>
                        <a href="{% url 'tools:user' %}?u={{request.requester.pk}}">{{ review.reviewer.user.get_full_name }}</a>
                    </td>
                </tr>                
            </table>
            <center>
            {% if review.review_type %}
                Reviewed as a Borrower
            {% else %}
                Reviewed as a Sharer
            {% endif %}
            <p class = "rate">
                {{review.rating}}
            </p>
            </center>
            <dir id = "scrollup">
                {{review.comment}}
            </dir>
    </dir>
</td>

tools/templates/tools/todo_review_block.html
{% load staticfiles %}

<td>
    <dir id="block">
            <table>
                <tr>
                    <td>
                        <img id="pic_small" src="{% static 'tools/user.png' %}"/>
                    </td>
                    <td>
                        <a href="{% url 'tools:user' %}?u={{request.requester.pk}}">{{ todoreview.todo_reviewee.user.get_full_name }}</a>
                    </td>
                </tr>                
            </table>
            <center>
                {% if todoreview.todo_review_type  %}
                    Borrowed
                {% else %}
                    Loaned you
                {% endif %}
            </center>
            <table>
                <tr>
                    <td>
                        {% include "tools/smallicon.html" %}
                    </td>
                    <td>
                        <a href="{% url 'tools:detail' todoreview.todo_tool.pk %}">{{ todoreview.todo_tool.tool_name }}</a>
                    </td>
                </tr>
            </table>
        <center>
            <a href="{% url 'tools:review'%}?r={{todoreview.pk}}"id="button">Review</a>
        </center>
    </dir>
</td>

tools/templates/tools/tool_block.html
{% load staticfiles %}

<td>
    <dir id="block">
        <table>
            <tr>
                <td>
                    {% include "tools/status.html" %}
                </td>
                <td>
                    <p class="title">
                        {{ tool.tool_name }}
                    <p>
                </td>
            </tr>
        </table>
        <center>
            {% include "tools/icon.html" %}
            <a href="{% url 'tools:detail' tool.id %}"id="button">More</a>
        </center>
    </dir>
</td>

tools/templates/tools/user_block.html
{% load staticfiles %}

<td>
    <dir id="block">
        <center>
            {{ user.user.get_full_name }}
            <br>
            <img id="pic" src="{% static 'tools/user.png' %}"/>
            <a href="{% url 'tools:user' %}?u={{user.pk}}"id="button">More</a>
        </center>
    </dir>
</td>